### PR TITLE
Cast MagicLink's UUID to a string when initially set

### LINKED ISSUE #112: setMagiclinkId(): Argument #1 ($magiclinkId) must be of type string, LazyUuidFromString given
`setMagiclinkId()` on `ActionAbstract` requires a string, but `Str::uuid()` in Laravel 9+ will return a `LazyUuidFromString`, which isn't being cast.

Casting it to a string in the `creating()` observe resolves this issue.

### PR DESCRIPTION
**Pull request by rossbearman**
Resolves #112.

### CODE REVIEW

**Comment by rossbearman** [comment]
The failing PHPStan test is unrelated to this change.

**Comment by cesargb** [comment]
@rossbearman Its true, the fail with phpStan is not related with this PR. 

I want merge your PR, Can you reopen?

**Comment by cesargb** [comment]
I reopen your PR

**Comment by rossbearman** [comment]
Hi @cesargb, I realised the issue wasn't directly related to `laravel-magiclink`. The failure was only happening at my end because `declare(strict_types=1);` was being injected everywhere by a rogue Pint configuration. 

The issue isn't present after pulling in a clean version of the package, as `LazyUuidFromString` gets cast automatically when `declare(strict_types=1);` isn't present.

**Pull request closed without merging**
